### ISSUE TITLE
WPA2 PMK file format not supported

### ISSUE THREAD

**Issue by Baesm** [Coalfire-Research/npk#11]
When following the official PMK hashcat guide (https://hashcat.net/forum/thread-7717.html) we reach a format that is supported by hashcat, but not by our hashcat installs on the AWS. 

It's the format ending on ".16800" which seems to be required to crack PMKID(s).

Error log from AWS: 

`Credentials loaded

[ '--quiet',

  '-O',

  '--remove',

  '--potfile-path=/potfiles/i-0d58c3a1967974a23.potfile',

  '-o',

  '/potfiles/cracked_hashes-i-0d58c3a1967974a23.txt',

  '-w',

  '4',

  '-m',

  2501,

  '-a',

  0,

  '-r',

  '/root/npk-rules/NSAKEY.v2.dive.rule.txt',

  '/root/hashes.txt',

  '/root/npk-wordlist/rockyou.txt' ]

Found status report in output

[31mnvmlDeviceGetFanSpeed(): Not Supported[0m

[31mnvmlDeviceGetFanSpeed(): Not Supported[0m

[31mnvmlDeviceGetFanSpeed(): Not Supported[0m

[31mnvmlDeviceGetFanSpeed(): Not Supported[0m

[33mHashfile '/root/hashes.txt': Invalid hccapx signature[0m

[31mNo hashes loaded.[0m

Caught error: TypeError: Cannot read property 'split' of undefined

Died with code 255 and signal 0`

**Comment by c6fc** [comment]
Hi @Baesm - I believe this was fixed in commit 39cc624. Can you please do the following and report back?

1. Run `git pull` from the npk directory
2. Re-run deploy.sh
3. Use the 'File Management' link to delete the hccapx file you'd uploaded
4. Re-upload the file through the 'New Campaign' page
5. Re-run the campaign

^ This should have you back up and running. Let me know if the error persists.

**Comment by c6fc** [comment]
Any luck with this @Baesm ?
