### ISSUE TITLE
Multi-Instance campaign not "sharing" workload as expected

### ISSUE THREAD

**Issue by ArchitektApx** [Coalfire-Research/npk#126]
I deployed v2 and started a campaign with more than one instance.

**Expected behavior:**
The campaign is distributed over all instances equally, i.e. with 2 instances each does 50% of the campaign, with 4 instances each does 25% of the campaign. Pretty much what the time-estimate would make you believe.

**Actual behavior:** 
Each Instance just does the same Hashcat job and gets the same results. There seems to be no benefit in using more than one instance. The campaign just cancels because it hits the time/money limit as each instance now has to do the full workload.

Did I do anything wrong or have I misunderstood the usecase for multiple instances?

**Comment by c6fc** [comment]
How do you know that this is occurring?

**Comment by ArchitektApx** [comment]
Gonna close this as I'm not able to reproduce the issue after doing a clean re-deploy.
Seems it was an issue on my side

**Comment by c6fc** [comment]
FYI, if you were going off of the node potfiles, it's expected that they would all have identical output by the end of the campaign. It shares the results among all the nodes so that they don't spend effort trying to crack a hash that was already cracked by another node. The same result appearing across multiple nodes is just evidence that this feature is working as intended.

I hope that helps!
