### ISSUE TITLE
WPA/WPA2 cracking with hccapx or cap files not working

### ISSUE THREAD

**Issue by ipiqadm** [Coalfire-Research/npk#138]
Hello,

Curious if any improvements or changes have been made to NPK as far as resolving issues with hccapx files used for WPA/WPA2 cracking? Have some team members here that have been unable to get hccapx file to work with NPK since we implemented it. Granted we are using the version from around August 2020 and I see that there were recent changes, but unknown if any of them resolve these problems with hccapx not being able to be used.

**Comment by c6fc** [comment]
Can you post the instance logs of your campaigns that are failing with WPA/WPA2?

Also, would you be willing to DM me an example hccapx file that you're having issues with? The original issues for that were address back in early 2018, and I've not caught wind of any similar issues.

**Comment by c6fc** [comment]
I tested the hccapx file you sent, and it worked on the first try on the current Master branch release, using WPA/WPA2 hash type on a g3 instance. Could you tell me more about the campaign configuration you're using?

One 'gotcha' with Hashcat and WPA is that if you're using dictionaries with words under 8 characters, it will discard them BEFORE applying rules. This means that if you're using the ACDC dictionary in NPK (which is all 7 characters or less), the campaign will run but hashcat will ignore the entire dictionary.

If you can hook me up with the instance logs for a failed WPA/WPA2 campaign, that would help quite a bit. Otherwise, just pull the new master and re-run the deploy to upgrade to the current release.

**Comment by c6fc** [comment]
I'm going to close this for now. Let me know if the issue persists.
