### ISSUE TITLE
Hashlist upload fails with large files due to multipart upload

### ISSUE THREAD

**Issue by hallo394505343** [Coalfire-Research/npk#158]
Tested with 24mb hash file through the NPK campaign builder GUI. Problematic if you are testing a larger hashlist.

the error:

https://media.discordapp.net/attachments/829233864572534805/870811552775831603/unknown.png

**Comment by c6fc** [comment]
This has been fixed in c6fc/npk repo in the api_rewrite branch. Instead of trying to handle large files with JavaScript, the File Management console now has a spot that you can use to upload files of any size.

the api_rewrite branch will be promoted to main soon, but it's available for testing right now if you want to give it a shot.
