### ISSUE TITLE
JWT problem

### ISSUE THREAD

**Issue by mrWhiteCrow** [Coalfire-Research/npk#18]
Guys first of all its a very cool project. 
Yesterday I run a new campain trying to crack a **jwt** with a wordlist (rockyou).
The Campaign is still starting, but I run it more than 10 hours ago.
Amazon already took the mony  that I have assigned for that.
but the dasboard says _"cost 0"._
![image](https://user-images.githubusercontent.com/12241058/57764893-43a16e80-76fc-11e9-9df2-a37c53149c69.png)
 
I  dont think that your project is currently supporintg in the correct way the jwt cracking could you please double check.

**Comment by c6fc** [comment]
It's likely that your instances aren't coming up, and your Spot Fleet request never left the state 'Starting', which is why this is happening. This can be due to a few reasons, like account limitations or having not subscribed to the NVidia AMI.

Can you answer the following to help me track down the problem?
1. Do you have logs appearing in File Management for those nodes?
2. In your Spot Fleet History within the AWS Console, do you see errors associated with your NPK fleet?
3. Have you subscribed to the NVidia AMI?

**Comment by mrWhiteCrow** [comment]
yes I have subscribed i the  NVidia AMI?

**Comment by c6fc** [comment]
How about the rest?
