### ISSUE TITLE
Error parsing response JSON

### ISSUE THREAD

**Issue by tratteur** [Coalfire-Research/npk#28]
Hi there.
NPK is up and running, I can log in and upload some hashes.
I have the test NTLM hash of 'b4b9b02e6f09a9bd760f388b67351e2b' from the haschat examples - which should be cracked with an a-z mask of 7 characters.

I select the various options (mask only, no wordlists) but whenever I submit a job I get:

Error: Error parsing response JSON. 

There's no errors in the file management area - any other crack types such as 16800 (WPA PMKID) and NTLM with wordlists do not run either.

Any suggestions gratefully received.

**Comment by c6fc** [comment]
Is this happening when you go to save a new campaign? Or when you go to upload a hash file?

If it's the former, I have a few follow-up questions:
1. Does the campaign appear in the dashboard after you get the error?
2. If you look in the Web Developer panel of your Browser, does it give any other indication about a failed request? Such as an HTTP response code of 500?
3. If you open your AWS account and go to CloudWatch Logs for the api_proxy_handler, do you see an error?

If there's nothing that stands out, please grab the full log event from CloudWatch for the api_proxy_handler for when this fails, and PM it to me.

Thanks in advance.

**Comment by tratteur** [comment]
Hi there. 
This was happening when I tried to add a campaign - that's now working, but when I do 'start' from the manage campaigns option I'm still getting the same error.
I looked in CloudWatch, and unless I'm missing something I'm not seeing any errors or any logs at all - there's some metrics there.

The only thing that sticks out when I do 'start' in the Developer Console (Firefox) is:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at 
https://4oad1rmbh3.execute-api.us-west-2.amazonaws.com/v1/userproxy/campaign/55784b39-7572-47dd-94c0-ab4ba60d5830. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

**Comment by cyrinux** [comment]
Hi,
I think a got the same problem here https://github.com/Coalfire-Research/npk/issues/32
Any news on the problem?

**Comment by c6fc** [comment]
This is likely because of an error in the Lambda function called 'proxy_api_handler'.

If you go to CloudWatch within AWS and view the log group for proxy_api_handler, you should see a verbose error there along with the full body of the request. Please DM both the full body and the error to me, and I'll be able to help troubleshoot.

**Comment by c6fc** [comment]
If you are getting the message 'Error parsing response JSON' when submitting or attempting to start a campaign, follow the instructions below for help getting it fixed.

This happens because CloudFront and Lambda both handle requests differently for different geographic regions, and sometimes it doesn't include a piece that the API expects to see. 

For help troubleshooting, please gather the following information and send it to me via a direct message. The contents of the error and request can contain sensitive information unique to your deployment, so please don't post them publicly.

- [ ] Please use the web developer panel in your browser to show the request and response that caused the error. Request Headers and Response Headers are especially useful. A screenshot is ideal.
- [ ] Log into your AWS Account, navigate to the CloudWatch service, and inspect the logs for the 'proxy_api_handler' log group (this should appear in Oregon). The logs will look similar to this:

![Selection_114](https://user-images.githubusercontent.com/143415/60362505-54512f80-999e-11e9-8ff1-9ded82a7dc26.png)

- [ ] Locate the error, along with the closest 'Received event' log entry above it. Copy the contents of both, and include them in your message to me.

Once I've received the message, I'll work on troubleshooting the issue and will issue a fix. Thanks for using NPK!

**Comment by c6fc** [comment]
I've moved this to a new pinned issue #36
