### ISSUE TITLE
False positive on "Total price exceeds campaign limits"?

### ISSUE THREAD

**Issue by braimee** [Coalfire-Research/npk#37]
Hi,

I was about to start a crack job (with 2 p3.8xlarge) that will run about 24 hours.  When I hit execute I get:

````
Warning: Total price exceeds campaign limits. Your instances may terminate earlier than you intend.
````

In my `npk-settings.json` I have $200 has the max campaign price.  

What else could be triggering this limits error?

Thanks,
Brian

**Comment by c6fc** [comment]
That's just a warning, not an error. It won't prevent you from launching a campaign.

It's currently hardcoded to $100 in `site-content/angular/controllers/npkMainCtrl.js` on line 1131. I haven't configured it to reference the max campaign limit set in the npk-settings yet. You can ignore this, since it doesn't actually stop you from doing anything.

The `spot_monitor` Lambda function is the only component responsible for enforcing the max campaign price as set in npk-settings. It'll let campaigns run until they actually exceed the price, then it'll terminate the associated instances.
