### ISSUE TITLE
Total Duration computation

### ISSUE THREAD

**Issue by PauloASilva** [Coalfire-Research/npk#65]
Hi,
First of all thanks for the effort put on NPK :clap: 

Can you please explain the formula used to compute [`totalDuration`][1]?

```
$scope.totalDuration = $scope.totalKeyspace / ($scope.gpus[$scope.selectedInstance] * ($scope.instances[$scope.selectedInstanceGeneration].hashes /4));
```

* What does `$scope.instances[$scope.selectedInstanceGeneration].hashes /4` mean?
* For a Mask-only attack shouldn't the `maskDuration` be the same than `totalDuration`?

[1]: https://github.com/Coalfire-Research/npk/blob/8ed3b47ad778bbbc2806789a2fbc0c2b7adf4b28/site-content/angular/controllers/npkMainCtrl.js#L882

Cheers,
Paulo A. Silva

**Comment by c6fc** [comment]
The formula is:
duration = keyspace / (GPU hashrate * GPU Count / 4)

The reason it's divided by 4 is because the benchmark hashrates are not representative of actual performance against wordlist campaigns, which can result in the tool recommending far less time that the campaign realistically needs. Since there's no easy way to benchmark hashcat under load, I cheated and forced the algorithm to assume a more conservative performance number. Since there is currently no way to resume an underscoped campaign, but an overscoped one will terminate the instances on completion, I erred on the side of quoting longer durations.
