### ISSUE TITLE
NPK Shows 0% Success Rate

### ISSUE THREAD

**Issue by bzekanovic** [Coalfire-Research/npk#70]
Noticed that NPK shows 0% success rate on completed campaigns, but some of the campaigns do have cracked hashes.

**Comment by bzekanovic** [comment]
Keep in mind that this is not consistent.

**Comment by c6fc** [comment]
If you open the campaign manager, is there anything consistent about the campaigns that incorrectly report 0 hashes? This number comes from parsing the Hashcat output directly, so I'm curious if there's a particular hash type that is changing hashcat's output somehow.

**Comment by bzekanovic** [comment]
@c6fc 
This bug seems to be caused by job completing within couple of minutes. The campaigns where campaign completes within minutes, I am not able to see metrics, but works just fine if is longer than approx 10 min. Also, noticed that instance status will go from Active to Error if job completes in less than 10 min. 

I hope this helps with this bug and you guys can implement some kind of fix. 

Thank you :)

**Comment by c6fc** [comment]
Thanks @bzekanovic - this is a known issue and is actually a limitation with hashcat. The 'hashes cracked' number reported by the UI is based on status reports generated by hashcat (literally a VTY wrapper pressing 's' while hashcat is running). Since hashcat exits silently when the job is done, that means any hashes cracked in the last ~1 minute of the cracking job won't get reported in the UI.

This is especially apparent if you run a job that doesn't even last long enough to get a status update at all (Such as an NTLM job with a wordlist alone); it starts and finishes before the VTY wrapper can coax a single status report out of it.

I'll see if I can add a bit after the job completes to send a final status update based on how many entries are in the potfile. That might just fill the gap the way you want :D

**Comment by c6fc** [comment]
I added this a while ago in v2, and I confirmed yesterday that it is functional with instantly-completing campaigns.
